### ISSUE TITLE
Concurrent leave results in stale entries

### ISSUE THREAD

**Issue by ghost** [koalazak/redis-registry#1]
I'm calling leave() for all services that have been joined before. Those leave() calls are concurrent, i.e. I don't wait for the callback of the first service before calling leave() on the second. In this case, some services are not deleted from redis. Also, I don't call leave() in the same order as join() before.

I suspect the following lines in leave() to be the problem:
`var i = services.indexOf(next);
if (i > -1) services.splice(next, 1);`

Should the splice function not be called with `i` instead of `next` as first parameter?
`if (i > -1) services.splice(i, 1);`
With this patch, it seems to work fine.

**Comment by koalazak** [comment]
fixed, thx
